name: Build Chromium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  multiarch_build_latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ 'linux/amd64', 'linux/arm64', 'linux/386', 'linux/arm/v7' ]
        chromium:
          - version: 'latest'
            snapshot: 'false'
          - version: '116.0.5845.180-1~deb12u1'
            snapshot: 'true'
          - version: '117.0.5938.149-1~deb12u1'
            snapshot: 'true'
          - version: '118.0.5993.70-1~deb12u1'
            snapshot: 'true'
    continue-on-error: true
    name: Build ${{ matrix.platform }} with Chromium ${{ matrix.chromium.version }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build ${{ matrix.platform }} with Chromium ${{ matrix.chromium_version.version }}
        run: |
          docker buildx build --progress=plain --build-arg CHROMIUM_VERSION=${{ matrix.chromium.version }} --build-arg CHROMIUM_SNAPSHOT=${{ matrix.chromium.snapshot }} --platform ${{ matrix.platform }} -t gulnap/chromium -f Dockerfile .
